### ISSUE TITLE
connect to host 4 port 22: Invalid argument

### ISSUE THREAD

**Issue by leon8889** [ataudt/aneufinder#1]
I am trying to run Aneufinder(inputfolder=infolder, outputfolder=outfolder,format="bam", numCPU=cpu, method=c("HMM","dnacopy"),pairedEndReads = TRUE )

A config file is created and then I get the Message:
Setting up parallel execution with 4 CPUs ...ssh: connect to host 4 port 22: Invalid argument
and then nothing happens.

What is wrong here??

**Comment by ataudt** [comment]
Hi Leon,

I can reproduce your error by running
Aneufinder(..., numCPU="4")

The correct way to run it is
Aneufinder(..., numCPU=4)

Your variable 'cpu' most likely contains 4 as a string, not a number. Running
Aneufinder(..., numCPU=as.numeric(cpu))
should fix the issue.

Best,
Aaron

Dipl. Biol. (t.o.) Aaron Taudt | PhD Student | University Medical Center Groningen
European Research Institute for the Biology of Ageing (ERIBA) | Quantitative Epigenetics
A. Deusinglaan 1, gebouw 3226 | 9700 AD Groningen. | www.ERIBA.umcg.nlhttps://mail.umcg.nl/owa/UrlBlockedError.aspx
