### ISSUE TITLE
can we get bed files from aneufinder

### ISSUE THREAD

**Issue by proukakis** [ataudt/aneufinder#2]
Hello we are trying to compare single cell data calls made by Ginkgo, Aneufinder and QDNAseq. We can do this if we get either bed or vcf files from aneufinder. We cant work out if this is possible, it will be great if you can let me know. Thanks

**Comment by ataudt** [comment]
There should be a folder BROWSERFILES in the produced output if you run function Aneufinder(), which contains a gzipped BED file with all cells. This file can be directly uploaded to the UCSC genome browser. You can also export the files with more fine-grained control over the format with function exportCNVs().

**Comment by proukakis** [comment]
Many thanks

Sent from my iPhone

On 12 Jun 2017, at 1:04 pm, ataudt <notifications@github.com<mailto:notifications@github.com>> wrote:


There should be a folder BROWSERFILES in the produced output if you run function Aneufinder(), which contains a gzipped BED file with all cells. This file can be directly uploaded to the UCSC genome browser. You can also export the files with more fine-grained control over the format with function exportCNVs().
