### ISSUE TITLE
Multiple issues with `binReads`

### ISSUE THREAD

**Issue by mschubert** [ataudt/aneufinder#3]
I've found the following potential issues when looking at the code of the `binReads` function and how it is called from `Aneufinder`.

#### `binReads` calculates binning for each file it processes in parallel

Calculating the bins for multiple `bam` files should yield the same result as long as the assembly is the same. This has to be the case if `use.bamsignals=FALSE`, but also should be if `use.bamsignals=TRUE`.

Why then does Aneufinder generate the same bins again, and this in parallel for each `bam` file it processes? If I've got 50 `bam` files, this will calculate bins 50 times over:

https://github.com/ataudt/aneufinder/blob/master/R/binReads.R#L216-L237

#### It is not possible to make `binReads` run only on pre-calculated bins

There is 3 variables used to pass bins:

* `binsizes` - bins to calculate with a fixed size
* `reads.per.bin` - bins to calculate with a fixed read count
* `bins` - already calculated bins either from a file or `GRanges` object

The [documentation for `bins`](https://github.com/ataudt/aneufinder/blob/master/R/binReads.R#L15) states:

> A named `list` with `GRanges` containing precalculated bins produced by `fixedWidthBins` or `variableWidthBins`.

This, however, is not how it is used in the `Aneufinder` function; here, bin sizes are passed that are **not** calculated yet:

https://github.com/ataudt/aneufinder/blob/master/R/Aneufinder.R#L221

In addition, the `parallel.helper` function that is supposed to bin reads doesn't do anything with existing bins: 

https://github.com/ataudt/aneufinder/blob/master/R/Aneufinder.R#L217-L224

**Comment by ataudt** [comment]
Hi Michael,

`binReads()` has the capability to do the binning for each file in parallel. This has historical reasons.
It is possible to make `binReads` run on only pre-calculated bins, with the argument
* `bins` - already calculated bins either from a file or `GRanges` object

It is used like that in the `Aneufinder()` function:
https://github.com/ataudt/aneufinder/blob/master/R/Aneufinder.R#L224
			binReads(file=file, assembly=chrom.lengths.df, pairedEndReads=conf[['pairedEndReads']], binsizes=NULL, variable.width.reference=NULL, reads.per.bin=rpbin.todo, __bins=bins[as.character(binsizes.todo)]__, chromosomes=conf[['chromosomes']], remove.duplicate.reads=conf[['remove.duplicate.reads']], min.mapq=conf[['min.mapq']], blacklist=conf[['blacklist']], outputfolder.binned=binpath.uncorrected, save.as.RData=TRUE, reads.store=conf[['reads.store']], outputfolder.reads=readspath, use.bamsignals=conf[['use.bamsignals']])

**Comment by mschubert** [comment]
Hi Aaron,

> It is possible to make binReads run on only pre-calculated bins

If I'm not completely mistaken, this is not possible. The code for `binReads` always calculates new bins, even if I supply pre-calculated bins with the `bins` argument.

This is what I marked [here](https://github.com/ataudt/aneufinder/blob/master/R/binReads.R#L216-L237). Either `variable.width.reference` is `NULL` where it will calculate new fixed bins, or it is not `NULL` where it will calculate new variable size bins.

**Comment by ataudt** [comment]
Hi Michael,

you are correct that `binsReads()` always calls `fixedWidthBins()`. However, if the argument `binsizes=NULL`, `fixedWidthBins()` will just return an empty list, so computation time is negligible.

The call `binReads(..., binsizes=NULL, bins=precalculatedBinsList)` should not re-calculate the bins. It's also true that this doesn't work with `variable.width.reference != NULL`.

**Comment by mschubert** [comment]
So, the way to call the function to only use pre-calculated bins would be to:

* set `binsizes=NULL`
* leave `variable.width.reference` as `NULL` (because this is not used in this case anyway)
* supply the `bins` argument

Right?

Ok, that seems to work.
