### ISSUE TITLE
Plots assigned wrong identifiers in heatmapGenomewide

### ISSUE THREAD

**Issue by mschubert** [ataudt/aneufinder#4]
`heatmapGenomewide` gets confused if any model in the list of `hmms` has an empty `segments` variable and plots the wrong identifiers for samples.

It would be better to either drop these samples or throw an error.

**Comment by ataudt** [comment]
Thanks for the info. I am working on including strandseq capabilities into aneufinder and have encountered the same bug. It's corrected in branch 'stepsize' which I will soon merge with master.
