### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by EularTang** [ataudt/aneufinder#5]
Hi,
When I click the hyperlink 'vignette', it will prompt “404 page not found‘’.
I think the pdf no longer exists， what happened?
Thank you for your attention.
(https://github.com/ataudt/aneufinder/blob/master/vignettes/AneuFinder.pdf)

**Comment by ataudt** [comment]
I redirected the link. The Bioconductor maintainers had deleted the static PDF and this change was carried over to the github repository. Thank you for your comment.
