### ISSUE TITLE
Package check failure with cowplot release candidate

### ISSUE THREAD

**Issue by clauswilke** [ataudt/aneufinder#7]
I'm about to release cowplot 1.0 and your package currently doesn't pass a package check with the cowplot release candidate. The problem is in this example:
https://github.com/ataudt/aneufinder/blob/adb74437a5b4bf3dfc15490121e05d02fdb2ca08/R/blacklist.R#L22

The cowplot package doesn't automatically attach ggplot2 anymore, and therefore the example  breaks without an explicit `library(ggplot2)`. If you depend on an attached ggplot2 in multiple places, you can also ggplot2 from Imports to Depends in your description file, though generally it is now discouraged to have numerous packages in Depends.

There are also a few other important changes to cowplot. I suggest you read through the release notes and make sure your package works with the cowplot release candidate.
https://github.com/wilkelab/cowplot/blob/master/NEWS

I expect to do the CRAN release in the 2nd week of July.

**Comment by ataudt** [comment]
This issue has been addressed. Thank you.
