### ISSUE TITLE
Binread, Error in match(x, table, nomatch = 0L) :    'match' requires vector arguments

### ISSUE THREAD

**Issue by ghost** [ataudt/aneufinder#9]
I'm trying to generate bin data from GRanges object that I made from:

```
raw_reads=bam2GRanges(bamfile,remove.duplicate.reads = TRUE,min.mapq = 10,blacklist = blacklist)
```

And this turned out to work. However when I try:
```
bins_reads=binReads(raw_reads,
                    assembly=genome,
                    chromosomes=chromosomes,
                    binsizes=c(40000,80000,100000,200000,500000))
```
It gives me the error massage: ```Subsetting specified chromosomes ...Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments```

The error can be traced back to: 
```
traceback()
3: seqnames(data) %in% chroms2use
2: data[seqnames(data) %in% chroms2use]
1: binReads(raw_reads, assembly = genome, chromosomes = chromosomes, 
       binsizes = c(40000, 80000, 100000, 200000, 500000))
```
Please help me understand what is going on here. Thank you so much!

**Comment by ghost** [comment]
When I try ```seqnames(raw_reads) %in% chroms2use``` 
This also works. So I have no idea what went wrong.

**Comment by ataudt** [comment]
Can you post the whole script? Specifically, what is in "genome" and "chromosomes"?
